# Generated by Django 4.2.7 on 2025-10-03 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # Crear modelo CodigoProcedimiento
        migrations.CreateModel(
            name='CodigoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del procedimiento (ej: ART. 254 CPC)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del procedimiento', max_length=200)),
                ('tipo_documento', models.CharField(choices=[('demanda', 'Demanda'), ('contestacion', 'Contestación'), ('replica', 'Réplica'), ('duplica', 'Dúplica'), ('recurso_apelacion', 'Recurso de Apelación'), ('recurso_casacion', 'Recurso de Casación'), ('recurso_revision', 'Recurso de Revisión'), ('recurso_queja', 'Recurso de Queja'), ('recurso_proteccion', 'Recurso de Protección'), ('recurso_amparo', 'Recurso de Amparo'), ('recurso_amparo_economico', 'Recurso de Amparo Económico'), ('incidente', 'Incidente'), ('excepcion', 'Excepción'), ('reconvencion', 'Reconvención'), ('terceria', 'Tercería'), ('intervencion', 'Intervención'), ('desistimiento', 'Desistimiento'), ('allanamiento', 'Allanamiento'), ('transaccion', 'Transacción'), ('conciliacion', 'Conciliación'), ('mediacion', 'Mediación'), ('arbitraje', 'Arbitraje'), ('medida_cautelar', 'Medida Cautelar'), ('embargo', 'Embargo'), ('secuestro', 'Secuestro'), ('otro', 'Otro')], max_length=30)),
                ('tipo_procedimiento', models.CharField(choices=[('ordinario', 'Procedimiento Ordinario'), ('sumario', 'Procedimiento Sumario'), ('ejecutivo', 'Procedimiento Ejecutivo'), ('monitorio', 'Procedimiento Monitorio'), ('laboral', 'Procedimiento Laboral'), ('familia', 'Procedimiento de Familia'), ('cobranza', 'Procedimiento de Cobranza'), ('violencia_intrafamiliar', 'Violencia Intrafamiliar'), ('alimentos', 'Alimentos'), ('divorcio', 'Divorcio'), ('cuidado_personal', 'Cuidado Personal'), ('relacion_directo', 'Relación Directo y Regular'), ('adopcion', 'Adopción'), ('menores', 'Menores'), ('adolescentes', 'Adolescentes'), ('penal', 'Procedimiento Penal'), ('administrativo', 'Procedimiento Administrativo'), ('tributario', 'Procedimiento Tributario'), ('otro', 'Otro')], max_length=30)),
                ('dias_plazo', models.IntegerField(help_text='Días de plazo automático', validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_dia', models.CharField(choices=[('habil', 'Días Hábiles'), ('corrido', 'Días Corridos')], default='habil', max_length=10)),
                ('articulo_cpc', models.CharField(blank=True, help_text='Artículo del Código Procesal Civil', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del procedimiento')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones especiales')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código de Procedimiento',
                'verbose_name_plural': 'Códigos de Procedimiento',
                'ordering': ['codigo', 'tipo_documento'],
            },
        ),
        # Agregar campos a PlazoJudicial
        migrations.AddField(
            model_name='plazojudicial',
            name='codigo_procedimiento',
            field=models.ForeignKey(blank=True, help_text='Código de procedimiento civil (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plazos.codigoprocedimiento'),
        ),
        migrations.AddField(
            model_name='plazojudicial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plazojudicial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plazojudicial',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plazos', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
