# Generated by Django 4.2.7 on 2025-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='colegio_profesional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(help_text='Formato: 12.345.678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
    ]
