version: '3.8'

services:
  db:
    image: postgres:15
    container_name: calendario_judicial_db_dev
    environment:
      POSTGRES_DB: calendario_judicial_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    container_name: calendario_judicial_web_dev
    command: >
      sh -c "python manage.py migrate --settings=calendario_judicial.settings_dev &&
             python manage.py runserver 0.0.0.0:8000 --settings=calendario_judicial.settings_dev"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/calendario_judicial_dev
      - SECRET_KEY=clave-desarrollo-no-segura
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data_dev:
