# Generated by Django 4.2.7 on 2025-10-04 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_colegio_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_licencia',
            field=models.CharField(blank=True, help_text='Número de licencia profesional (formato: 123456-7 para abogados)', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Formato de licencia inválido', regex='^[0-9\\-A-Za-z]+$')], verbose_name='Número de Licencia'),
        ),
    ]
