# Generated by Django 4.2.7 on 2025-10-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0003_auto_20251003_1648'),
    ]

    operations = [
        # Eliminar el campo fecha_modificacion de la migración original
        migrations.RemoveField(
            model_name='plazojudicial',
            name='fecha_modificacion',
        ),
    ]
