# Generated by Django 4.2.7 on 2025-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0007_alter_plazojudicial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazojudicial',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Documento adjunto relacionado con el plazo', null=True, upload_to='documentos_plazos/%Y/%m/%d/'),
        ),
    ]
