# Generated by Django 4.2.7

from django.db import migrations, models
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlazoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('demanda', 'Demanda'), ('contestacion', 'Contestación'), ('replica', 'Réplica'), ('duplica', 'Dúplica'), ('alegatos', 'Alegatos'), ('recurso_apelacion', 'Recurso de Apelación'), ('recurso_casacion', 'Recurso de Casación'), ('recurso_proteccion', 'Recurso de Protección'), ('recurso_amparo', 'Recurso de Amparo'), ('incidente', 'Incidente'), ('recurso_hecho', 'Recurso de Hecho'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('procedimiento', models.CharField(choices=[('civil', 'Civil'), ('laboral', 'Laboral'), ('familia', 'Familia'), ('penal', 'Penal'), ('cobranza', 'Cobranza'), ('arrendamiento', 'Arrendamiento'), ('consumo', 'Consumo'), ('otro', 'Otro')], max_length=50, verbose_name='Procedimiento')),
                ('dias_plazo', models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name='Días de Plazo')),
                ('tipo_dia', models.CharField(choices=[('habil', 'Hábil'), ('corrido', 'Corrido')], max_length=10, verbose_name='Tipo de Día')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('rut_causa', models.CharField(max_length=20, verbose_name='RUT de la Causa')),
                ('clave_cliente', models.CharField(max_length=100, verbose_name='Clave del Cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('esperando_proveido', 'Esperando Proveído'), ('corriendo', 'Corriendo'), ('suspendido', 'Suspendido'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Plazo Judicial',
                'verbose_name_plural': 'Plazos Judiciales',
                'ordering': ['fecha_vencimiento', 'fecha_inicio'],
            },
        ),
    ]
