# Generated by Django 4.2.7 on 2025-10-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0002_auto_20251003_1643'),
    ]

    operations = [
        # Eliminar el campo fecha_creacion de la migración original
        migrations.RemoveField(
            model_name='plazojudicial',
            name='fecha_creacion',
        ),
    ]
