# Generated by Django 4.2.7 on 2025-10-03 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0006_fix_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plazojudicial',
            options={'ordering': ['-fecha_vencimiento'], 'verbose_name': 'Plazo Judicial', 'verbose_name_plural': 'Plazos Judiciales'},
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='clave_cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='dias_plazo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('esperando_proveido', 'Esperando Proveído'), ('corriendo', 'Corriendo'), ('suspendido', 'Suspendido'), ('vencido', 'Vencido')], default='corriendo', max_length=20),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='procedimiento',
            field=models.CharField(choices=[('ordinario', 'Procedimiento Ordinario'), ('sumario', 'Procedimiento Sumario'), ('ejecutivo', 'Procedimiento Ejecutivo'), ('monitorio', 'Procedimiento Monitorio'), ('laboral', 'Procedimiento Laboral'), ('familia', 'Procedimiento de Familia'), ('cobranza', 'Procedimiento de Cobranza'), ('violencia_intrafamiliar', 'Violencia Intrafamiliar'), ('alimentos', 'Alimentos'), ('divorcio', 'Divorcio'), ('cuidado_personal', 'Cuidado Personal'), ('relacion_directo', 'Relación Directo y Regular'), ('adopcion', 'Adopción'), ('menores', 'Menores'), ('adolescentes', 'Adolescentes'), ('penal', 'Procedimiento Penal'), ('administrativo', 'Procedimiento Administrativo'), ('tributario', 'Procedimiento Tributario'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='rut_causa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='tipo_dia',
            field=models.CharField(choices=[('habil', 'Días Hábiles'), ('corrido', 'Días Corridos')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plazojudicial',
            name='tipo_documento',
            field=models.CharField(choices=[('demanda', 'Demanda'), ('contestacion', 'Contestación'), ('replica', 'Réplica'), ('duplica', 'Dúplica'), ('recurso_apelacion', 'Recurso de Apelación'), ('recurso_casacion', 'Recurso de Casación'), ('recurso_revision', 'Recurso de Revisión'), ('recurso_queja', 'Recurso de Queja'), ('recurso_proteccion', 'Recurso de Protección'), ('recurso_amparo', 'Recurso de Amparo'), ('recurso_amparo_economico', 'Recurso de Amparo Económico'), ('incidente', 'Incidente'), ('excepcion', 'Excepción'), ('reconvencion', 'Reconvención'), ('terceria', 'Tercería'), ('intervencion', 'Intervención'), ('desistimiento', 'Desistimiento'), ('allanamiento', 'Allanamiento'), ('transaccion', 'Transacción'), ('conciliacion', 'Conciliación'), ('mediacion', 'Mediación'), ('arbitraje', 'Arbitraje'), ('medida_cautelar', 'Medida Cautelar'), ('embargo', 'Embargo'), ('secuestro', 'Secuestro'), ('otro', 'Otro')], max_length=30),
        ),
    ]
