# Generated by Django 4.2.7 on 2025-10-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0008_plazojudicial_documento_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plazojudicial',
            name='rut_causa',
        ),
        migrations.AddField(
            model_name='plazojudicial',
            name='rol',
            field=models.CharField(blank=True, help_text='Serie de números para identificar el proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='plazojudicial',
            name='rut_cliente',
            field=models.CharField(blank=True, help_text='RUT del cliente', max_length=20),
        ),
    ]
